  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/ssm?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: P2ssw0rd
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 30000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true



mybatis-plus:
  mapper-locations: classpath:mapper/*.xml



server:
  port: 8080
  servlet:
    context-path: /
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

logging:
  config: classpath:logback.xml
