spring:
  profiles:
    active: dev



mybatis-plus:
  mapper-locations: classpath:mapper/*.xml



server:
  port: 8080
  servlet:
    context-path: /
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

logging:
  config: classpath:logback.xml
